name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  call-GJF:
    uses: beazt123/googlejavaformat-action/.github/workflows/reusableGJF.yml@main
    
  status:
    needs: call-GJF
    runs-on: ubuntu-latest
    steps:
      - run: echo "Complete!"
